
# -Dserver.port=8081 -Deureka.instance.hostname=host01
spring:
  application:
    name: eureka-client01
  boot:
    admin:
      client:
        url: http://127.0.0.1:8001

server:
  port: 8081
  compression:
    enabled: true
  tomcat:
    threads:
      max: 3
      min-spare: 1
    max-connections: 20
    accept-count: 10



eureka:
  instance:
    hostname: host01
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true