
spring:
  profiles: 8081
  application:
    name: eureka-client01

server:
  port: 8081

eureka:
  instance:
    hostname: host01
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/

---
spring:
  profiles: 8082
  application:
    name: eureka-client01

server:
  port: 8082

eureka:
  instance:
    hostname: host02
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/

---
spring:
  profiles: 8083
  application:
    name: eureka-client01

server:
  port: 8083

eureka:
  instance:
    hostname: host03
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/