server:
  port: 8091
spring:
  application:
    name: consul-client01
  cloud:
    consul:
      host: localhost
      port: 8501
      discovery:
        hostname: host01
#        prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'



